### ISSUE TITLE
Classroom marked as inactive still shows up on org page

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#100]
To see example, go to hawaii's page: https://www.learnthelaw.org/legal-aid-society-hawaii

The first classroom, "How to Get Money Damages if Your Landlord Locks You Out Illegally," is marked as inactive but still appears in this list. I tried to filter it out in the view, but the taxonomy field "status" is not available to me.

Secondly, that inactive classroom looks wrong to users who are not logged in: https://www.learnthelaw.org/classroom/2187
Please try viewing it logged in as admin and logged out to see what I mean.

**Comment by emasters** [comment]
This is the same as #61 & #64. It's an old issue that requires a tweaking of the view that is building the Classroom list on the org page.
The actual classroom looks weird because it knows it isn't supposed to show the contents (or there is no contents to show) to anon users. Once the view is fixed this won't be available at all.
@kngfrank you should be able to tweak the View controlling the list to filter out things marked inactive.

**Comment by kngfrank** [comment]
I tried to filter it out in the view, but the taxonomy field "status" is not available to me.

**Comment by kngfrank** [comment]
All set. Closing.
