### ISSUE TITLE
Classroom titles appearing intermittently

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#29]
On my first few visits to this classroom, there was no title. After clicking through the steps a few times, it appeared.

The title on this page should read "My sample classroom."
http://dev.learnthelaw.org/classroom/2164

It is happening in this classroom also:
http://dev.learnthelaw.org/classroom/2112

This is my first visit to the page - no title:
![erm-test](https://cloud.githubusercontent.com/assets/4311947/11001271/64b95fa2-8474-11e5-8c06-789df8fe7678.JPG)

After clicking the step(s) a few times, the title appears. I've done nothing other than click the classroom step a bunch of times:
![erm-test2](https://cloud.githubusercontent.com/assets/4311947/11001315/981ecac6-8474-11e5-8d55-d23145812186.JPG)

**Comment by emasters** [comment]
This is a bit of a stumper. The page title is not getting set. It's supposed to happen as part of opening the view that shows the Classroom.

**Comment by emasters** [comment]
Not much of a stumper now. :) 
The panel that generates the page was using `%classroom:i18n-name` for the title. This doesn't work because we removed the internationalization bits. I replaced it with `%classroom:name`.

The panel that was updated is at `http://dev.learnthelaw.org/admin/structure/pages/nojs/operation/page-classrooms/handlers/page_classrooms_panel_context_5/content`.

Fixed on dev. Need to update classroom modules.
