### ISSUE TITLE
Can't add classroom entry

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#36]
Title loads. Nothing else does. But I can add and save an entry with just a title and then edit the entry. Weird!

**Comment by emasters** [comment]
This appears to have cleared up when I opened permissions for Organic Groups. See #31.

**Comment by kngfrank** [comment]
Looks good. I'll close it.

**Comment by emasters** [comment]
Reopening. Not sure why, but it isn't working right on www. Looking into permissions issue.

**Comment by emasters** [comment]
This appears to be an issue with OG roles and permissions. In order to create classroom entries properly authors must have the proper role and permission inside of the OG. Right now there is one role available: `administrator member`. Users with this role can control all aspects of an OG that they belong to, which is not something we want to use to widely.
I'm going to create an `editor member` role or look at assigning the site wide `editor` role to the an OG role. Either way this role will be set so that users who are members of an OG and have the editor role will be able to create Classroom Entries.

**Comment by emasters** [comment]
It is not possible to map broader sitewide roles to OG roles as a matter of security. I added an `editor member` role and gave it perms for creating Classroom Entries. Testing now.

**Comment by emasters** [comment]
Tests work. OG editor members can create Classrooms. Updated code on develop branch. Closing.
