### ISSUE TITLE
Shift site design to focus on organizations in order to provide better tracking and ux

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#75]
So that all URLs have the user's group name in them.

**Comment by emasters** [comment]
For this to work we need to rework the site structure to shift from people centric to organization centric. We need to have organization context in place to deal with how everything is handled.
More to come.

**Comment by emasters** [comment]
- Create context for organizations (Organic Groups)
- Everything then happens inside of the Org context
- Org admins and editors only exist inside of the Org context
- Classrooms (private taxonomy) are created as part of the Org context
- Content (Classroom Entries) are created as Org content
  The overall effect of this is to create a true site for the Org so that once anyone goes away from the home page of www.learnthelaw.org they will find themselves in a site that is managed by a legal aid org.

Getting this working looks feasible with the modules already installed on the site including Views, Context, and Organic Groups. Much of the navigation will need to be reworked to enforce context and it seems likely that there will need to be changes made to the Online Classroom module.  

In terms of developer time I'd estimate 18 - 20 hours to get an initial prototype put together and another 18 - 20 hours to for testing, tweaking, and deployment. I'd recommend that this be done as concentrated time over the course of a week or so. The work is sufficiently complex that it requires considerable focus and trying to d oit an hour here and hour there will only stretch the time needed.

In addition time will be needed to document the changes and inform the community.

**Comment by emasters** [comment]
See #82 as initial fix to implement the Org context features.

**Comment by emasters** [comment]
Initial work on redesign involves adding organization reference to the Classroom taxonomy and adding 2 panel pages to bring Classroom and Classroom Entries admin tabs to the Organization homepage. These tabs will be visible to org admins and editors. 
Implementing the Classroom reference to the organizations will require site admin editing of each Classroom term. See #83 
The new admin tabs for Classrooms (see #84) and Classroom Entries (see #85) provide the same level of access as the Classrooms link to the admin pages but keep all of the work in the context of the organization. There are navigation issues that remain to be worked out.

**Comment by emasters** [comment]
See #86 #87 #88 for more changes coming in this redesign.
