### ISSUE TITLE
Add Classroom Entries panel page and tab to Org context

### ISSUE THREAD

**Issue by emasters** [CCALI/learnthelaw#85]
This panel adds the Classroom Entries view to a tabbed page in the org context. It provides important org context for administering Classroom Entries.

**Comment by emasters** [comment]
Org admins and editors should be able to see all Clasroom Entries for an organization and edit those. Needs to be tested. 
There are also some navigation issues.

**Comment by KathyDaniels** [comment]
TESTED:  I see a "Classroom Entries" page and tab logged in both as an org admin and as an org editor.
Editor cannot create classrooms so, I cannot fully test this.  I can test with the class entries created by the org admin:
Org Admin:  can see and edit own classroom entries from the classroom entries tab
Org Editor:  can see classroom entries tab.   cannot see classroom entries on the tab (only classroom entries for the org were created by the org admin)  I cannot test whether or not the org editor can see their own entries because they can't create a classroom. (get error message:  "status field is required" when attempting to do so.)

**Comment by kngfrank** [comment]
Each role can now see all classrooms and all entries associated with the organization.

But editor and org admin cannot edit each other's classrooms.

**Comment by emasters** [comment]
As of 7/21/16 non-member logged in users can see the tab and the listing. This needs to be changed so the tab only shows to admins and editors of the group.
